// OWNER DASHBOARD — authentication, live booking lists, history, payments, customers and password change.
let token=localStorage.getItem('srt_owner_token')||'', allBookings=[];
const isDemo = token === 'demo-owner:local-preview';
function demoRead(key, fallback){ try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));}catch{return fallback;} }
function demoWrite(key,value){localStorage.setItem(key,JSON.stringify(value));}
function demoSummary(bookings,enquiries){return {totalBookings:bookings.length,pending:bookings.filter(b=>b.status==='Pending').length,confirmed:bookings.filter(b=>b.status==='Confirmed').length,completed:bookings.filter(b=>b.status==='Completed').length,cancelled:bookings.filter(b=>b.status==='Cancelled').length,estimatedValue:bookings.reduce((a,b)=>a+Number(b.fare||0),0),enquiries:enquiries.length};}
const $=s=>document.querySelector(s), money=n=>'₹'+Math.round(Number(n)||0).toLocaleString('en-IN');
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
async function api(url,options={}){
  if(isDemo){
    const bookings=demoRead('srt_demo_bookings',[]), enquiries=demoRead('srt_demo_enquiries',[]);
    const method=(options.method||'GET').toUpperCase();
    if(url==='/api/owner/summary') return demoSummary(bookings,enquiries);
    if(url==='/api/owner/bookings') return {bookings};
    if(url==='/api/owner/enquiries') return {enquiries};
    if(url==='/api/auth/change-password'){
      const body=JSON.parse(options.body||'{}'); const current=localStorage.getItem('srt_demo_owner_password')||'895987';
      if(body.currentPassword!==current) throw Error('Current password is incorrect.');
      if(String(body.newPassword||'').length<6) throw Error('New password must be at least 6 characters.');
      localStorage.setItem('srt_demo_owner_password',body.newPassword); return {message:'Password changed for this local preview.'};
    }
    const statusMatch=url.match(/^\/api\/owner\/bookings\/([^/]+)\/status$/), paymentMatch=url.match(/^\/api\/owner\/bookings\/([^/]+)\/payment$/), deleteMatch=url.match(/^\/api\/owner\/bookings\/([^/]+)$/);
    if(statusMatch && method==='PATCH'){const b=bookings.find(x=>x.id===decodeURIComponent(statusMatch[1]));if(!b)throw Error('Booking not found.');const body=JSON.parse(options.body||'{}');b.status=body.status;demoWrite('srt_demo_bookings',bookings);return {booking:b};}
    if(paymentMatch && method==='PATCH'){const b=bookings.find(x=>x.id===decodeURIComponent(paymentMatch[1]));if(!b)throw Error('Booking not found.');const body=JSON.parse(options.body||'{}');b.paymentStatus=body.paymentStatus;demoWrite('srt_demo_bookings',bookings);return {booking:b};}
    if(deleteMatch && method==='DELETE'){const id=decodeURIComponent(deleteMatch[1]);demoWrite('srt_demo_bookings',bookings.filter(x=>x.id!==id));return {message:'Booking deleted.'};}
    throw Error('Unsupported local preview action.');
  }
  options.headers={...(options.headers||{}),Authorization:`Bearer ${token}`};
  const r=await fetch(url,options),d=await r.json().catch(()=>({}));
  if(r.status===401){token='';localStorage.removeItem('srt_owner_token');window.location.href='owner-login.html';throw Error(d.message||'Session expired.')}
  if(!r.ok)throw Error(d.message||'Request failed.');return d
}
$('#logout')?.addEventListener('click',()=>{token='';localStorage.removeItem('srt_owner_token');window.location.href='owner-login.html'});$('#refreshDash')?.addEventListener('click',loadDashboard);
async function loadDashboard(){try{const [s,b,e]=await Promise.all([api('/api/owner/summary'),api('/api/owner/bookings'),api('/api/owner/enquiries')]);allBookings=b.bookings||[];updateInsight();const ongoing=allBookings.filter(isOngoing).length,upcoming=allBookings.filter(isUpcoming).length,paymentPending=allBookings.filter(x=>(x.paymentStatus||'Pending')==='Pending').length;$('#statTotal').textContent=s.totalBookings;$('#statPending').textContent=s.pending;$('#statConfirmed').textContent=s.confirmed;$('#statOngoing').textContent=ongoing;$('#statUpcoming').textContent=upcoming;$('#statCancelled').textContent=s.cancelled ?? allBookings.filter(x=>x.status==='Cancelled').length;$('#statCompleted').textContent=s.completed;$('#statPaymentPending').textContent=paymentPending;$('#statRevenue').textContent=money(s.estimatedValue);renderBookings();renderEnquiries(e.enquiries||[]);renderPayments();renderCustomers();renderReports()}catch(err){console.error(err);alert(err.message)}}
function isToday(d){const x=new Date(d),t=new Date();return x.toDateString()===t.toDateString()}
function isFuture(d){const x=new Date(d);x.setHours(23,59,59,999);return x>=new Date()}
function isOngoing(b){return b.status==='Confirmed' && isToday(b.date)}
function isUpcoming(b){return b.status==='Confirmed' && !isOngoing(b) && isFuture(b.date)}
function isHistory(b){return b.status==='Completed'||b.status==='Cancelled'||(b.status==='Confirmed'&&!isFuture(b.date))}
function updateInsight(){const ongoing=allBookings.filter(isOngoing),upcoming=allBookings.filter(isUpcoming),history=allBookings.filter(isHistory),pendingPay=allBookings.filter(b=>(b.paymentStatus||'Pending')==='Pending');$('#ongoingCount').textContent=ongoing.length;$('#upcomingCount').textContent=upcoming.length;$('#historyCount').textContent=history.length;$('#paymentPendingCount').textContent=pendingPay.length;renderTripCards('#ongoingCards',ongoing,'No trips are marked ongoing today.');renderTripCards('#upcomingCards',upcoming,'No upcoming confirmed trips.');renderTripCards('#historyCards',history,'No booking history yet.')}
function statusClass(s){return String(s||'Pending').toLowerCase()}
function renderTripCards(sel,items,empty){$(sel).innerHTML=items.length?items.map(b=>`<article class="booking-card"><div class="booking-card-head"><div><h4>${esc(b.id)}</h4><div class="route">${esc(b.from)} → ${esc(b.to)}</div></div><span class="status-pill ${statusClass(b.status)}">${esc(b.status)}</span></div><div class="meta"><span>👤 ${esc(b.name)}</span><span>📅 ${esc(b.date)}</span><span>🚐 ${esc(b.vehicle)}</span><span>👥 ${esc(b.passengers)}</span><span>💰 ${money(b.fare)}</span><span>💳 ${esc(b.paymentStatus||'Pending')}</span></div><div class="actions"><a class="mini-btn" href="tel:${esc(b.phone)}">☎ Call</a><a class="mini-btn" target="_blank" href="https://wa.me/91${esc(b.phone)}">💬 WhatsApp</a></div></article>`).join(''):`<div class="card"><p>${empty}</p></div>`}
function renderBookings(){const q=($('#bookingSearch')?.value||'').toLowerCase().trim(),filter=$('#bookingFilter')?.value||'All';const items=allBookings.filter(b=>(filter==='All'||b.status===filter)&&(!q||[b.id,b.name,b.phone,b.from,b.to,b.vehicle,b.package].join(' ').toLowerCase().includes(q)));$('#bookingRows').innerHTML=items.length?items.map(b=>`<tr><td><b>${esc(b.id)}</b></td><td>${esc(b.name)}<br><small>${esc(b.phone)}</small></td><td>${esc(b.from)} → ${esc(b.to)}${b.package?`<br><small>${esc(b.package)}</small>`:''}</td><td>${esc(b.date)}</td><td>${esc(b.vehicle)}</td><td><b>${money(b.fare)}</b></td><td><select class="action-select" data-payment="${esc(b.id)}">${['Pending','Paid','Failed','Refunded'].map(s=>`<option ${b.paymentStatus===s?'selected':''}>${s}</option>`).join('')}</select></td><td><select class="action-select" data-status="${esc(b.id)}">${['Pending','Confirmed','Completed','Cancelled'].map(s=>`<option ${b.status===s?'selected':''}>${s}</option>`).join('')}</select></td><td><a class="mini-btn" href="tel:${esc(b.phone)}">Call</a> <button class="mini-btn" data-delete="${esc(b.id)}">Delete</button></td></tr>`).join(''):'<tr><td colspan="9">No matching bookings.</td></tr>'}
function renderPayments(){const items=allBookings.slice().sort((a,b)=>(a.paymentStatus||'Pending').localeCompare(b.paymentStatus||'Pending'));$('#paymentRows').innerHTML=items.length?items.map(b=>`<tr><td><b>${esc(b.id)}</b></td><td>${esc(b.name)}</td><td>${money(b.fare)}</td><td>${esc(b.paymentStatus||'Pending')}</td><td><select class="action-select" data-payment="${esc(b.id)}">${['Pending','Paid','Failed','Refunded'].map(s=>`<option ${b.paymentStatus===s?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join(''):'<tr><td colspan="5">No payment records.</td></tr>'}
function renderCustomers(){const map={};allBookings.forEach(b=>{const key=b.phone||b.email||b.name;if(!map[key])map[key]={name:b.name,phone:b.phone,email:b.email,count:0,total:0};map[key].count++;map[key].total+=Number(b.fare||0)});const items=Object.values(map);$('#customerRows').innerHTML=items.length?items.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.phone)}</td><td>${esc(c.email||'-')}</td><td>${c.count}</td><td>${money(c.total)}</td></tr>`).join(''):'<tr><td colspan="5">No customers yet.</td></tr>'}
function renderReports(){const total=allBookings.reduce((a,b)=>a+Number(b.fare||0),0),paid=allBookings.filter(b=>b.paymentStatus==='Paid').reduce((a,b)=>a+Number(b.fare||0),0);const confirmed=allBookings.filter(b=>b.status==='Confirmed').length,cancelled=allBookings.filter(b=>b.status==='Cancelled').length;$('#reportText').innerHTML=`<div class="report-item">Total bookings<b>${allBookings.length}</b></div><div class="report-item">Booking value<b>${money(total)}</b></div><div class="report-item">Paid value<b>${money(paid)}</b></div><div class="report-item">Confirmed<b>${confirmed}</b></div><div class="report-item">Cancelled<b>${cancelled}</b></div><div class="report-item">Conversion view<b>${allBookings.length?Math.round(confirmed/allBookings.length*100):0}%</b></div>`}
function renderEnquiries(items){$('#enquiryRows').innerHTML=items.length?items.map(e=>`<tr><td>${esc(e.id)}</td><td>${esc(e.name)}</td><td>${esc(e.phone)}</td><td>${esc(e.email)}</td><td>${esc(e.message)}</td><td>${new Date(e.createdAt).toLocaleString()}</td></tr>`).join(''):'<tr><td colspan="6">No enquiries yet.</td></tr>'}
async function updateBooking(url,body){await api(url,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await loadDashboard()}
$('#bookingRows')?.addEventListener('change',async e=>{const s=e.target.closest('[data-status]'),p=e.target.closest('[data-payment]');try{if(s)await updateBooking(`/api/owner/bookings/${encodeURIComponent(s.dataset.status)}/status`,{status:s.value});if(p)await updateBooking(`/api/owner/bookings/${encodeURIComponent(p.dataset.payment)}/payment`,{paymentStatus:p.value})}catch(err){alert(err.message)}});
$('#paymentRows')?.addEventListener('change',async e=>{const p=e.target.closest('[data-payment]');if(!p)return;try{await updateBooking(`/api/owner/bookings/${encodeURIComponent(p.dataset.payment)}/payment`,{paymentStatus:p.value})}catch(err){alert(err.message)}});
$('#bookingRows')?.addEventListener('click',async e=>{const b=e.target.closest('[data-delete]');if(!b)return;if(!confirm('Delete this booking permanently?'))return;try{await api(`/api/owner/bookings/${encodeURIComponent(b.dataset.delete)}`,{method:'DELETE'});await loadDashboard()}catch(err){alert(err.message)}});
$('#bookingSearch')?.addEventListener('input',renderBookings);$('#bookingFilter')?.addEventListener('change',renderBookings);
$('#changePasswordForm')?.addEventListener('submit',async e=>{e.preventDefault();const msg=$('#passwordMessage');if($('#newPassword').value!==$('#confirmPassword').value){msg.textContent='New passwords do not match.';msg.style.color='#c0392b';return}try{const d=await api('/api/auth/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword:$('#currentPassword').value,newPassword:$('#newPassword').value})});msg.textContent=d.message;msg.style.color='#14733b';e.target.reset()}catch(err){msg.textContent=err.message;msg.style.color='#c0392b'}});
document.querySelectorAll('.owner-mobile-bar a').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.owner-mobile-bar a').forEach(x=>x.classList.remove('active'));a.classList.add('active')}));
if(!token){ window.location.href='owner-login.html'; } else { document.getElementById('dashboard')?.classList.remove('hidden'); loadDashboard(); }
